"""document_chunk_cascade

Revision ID: 43bfcfd9fc19
Revises: b8469a5ddaf5
Create Date: 2026-05-27 14:11:09.507963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401


revision: str = '43bfcfd9fc19'
down_revision: Union[str, None] = 'b8469a5ddaf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_chunks_knowledge_item_id_fkey', 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'knowledge_items', ['knowledge_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key('document_chunks_knowledge_item_id_fkey', 'document_chunks', 'knowledge_items', ['knowledge_item_id'], ['id'])
    # ### end Alembic commands ###
