"""agent_job_evolutionarist_fields

Revision ID: b44136b7d629
Revises: e2f3g4h5i6j7
Create Date: 2026-05-30 16:20:56.345466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401


revision: str = 'b44136b7d629'
down_revision: Union[str, None] = 'e2f3g4h5i6j7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_jobs', sa.Column('agent_type', sa.String(), nullable=False))
    op.add_column('agent_jobs', sa.Column('branch', sa.String(), nullable=False))
    op.add_column('agent_jobs', sa.Column('pr_url', sa.String(), nullable=True))
    op.add_column('agent_jobs', sa.Column('model_config_json', sa.JSON(), nullable=False))
    op.add_column('agent_jobs', sa.Column('conversation_id', sa.String(), nullable=True))
    op.add_column('agent_jobs', sa.Column('parent_job_id', sa.String(), nullable=True))
    op.add_column('agent_jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'agent_jobs', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agent_jobs', 'agent_jobs', ['parent_job_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('contacts_google_resource_name_key', 'contacts', type_='unique')
    op.drop_index('ix_contacts_google_resource_name', table_name='contacts')
    op.create_index(op.f('ix_contacts_google_resource_name'), 'contacts', ['google_resource_name'], unique=True)
    op.drop_constraint('meeting_action_items_task_id_fkey', 'meeting_action_items', type_='foreignkey')
    op.create_foreign_key(None, 'meeting_action_items', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.drop_index('uq_pending_contacts_user_email_pending', table_name='pending_contacts', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index('ix_places_is_saved', table_name='places')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_places_is_saved', 'places', ['is_saved'], unique=False)
    op.create_index('uq_pending_contacts_user_email_pending', 'pending_contacts', ['user_id', 'detected_email'], unique=True, postgresql_where="((status)::text = 'pending'::text)")
    op.drop_constraint(None, 'meeting_action_items', type_='foreignkey')
    op.create_foreign_key('meeting_action_items_task_id_fkey', 'meeting_action_items', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_contacts_google_resource_name'), table_name='contacts')
    op.create_index('ix_contacts_google_resource_name', 'contacts', ['google_resource_name'], unique=False)
    op.create_unique_constraint('contacts_google_resource_name_key', 'contacts', ['google_resource_name'])
    op.drop_constraint(None, 'agent_jobs', type_='foreignkey')
    op.drop_constraint(None, 'agent_jobs', type_='foreignkey')
    op.drop_column('agent_jobs', 'completed_at')
    op.drop_column('agent_jobs', 'started_at')
    op.drop_column('agent_jobs', 'parent_job_id')
    op.drop_column('agent_jobs', 'conversation_id')
    op.drop_column('agent_jobs', 'model_config_json')
    op.drop_column('agent_jobs', 'pr_url')
    op.drop_column('agent_jobs', 'branch')
    op.drop_column('agent_jobs', 'agent_type')
    # ### end Alembic commands ###
