export const navItems = [
  { label: "Chat", href: "/chat", icon: "MessageSquare" },
  { label: "Tasks", href: "/tasks", icon: "CheckSquare" },
  { label: "Reminders", href: "/reminders", icon: "Bell" },
  { label: "Meetings", href: "/meetings", icon: "Video" },
  { label: "Contacts", href: "/contacts", icon: "Users" },
  { label: "Calendar", href: "/calendar", icon: "CalendarDays" },
  { label: "Second Brain", href: "/second-brain", icon: "Brain" },
  { label: "Agent Jobs", href: "/agent-jobs", icon: "Cpu" },
  { label: "Artifacts", href: "/artifacts", icon: "Archive" },
  { label: "Cron Manager", href: "/cron", icon: "Clock" },
  { label: "Connectors", href: "/connectors", icon: "Plug" },
  { label: "Mnemon", href: "/memory", icon: "Database" },
  { label: "Settings", href: "/settings", icon: "Settings" },
] as const
