export const navItems = [
  { label: "Chat",         href: "/chat",         icon: "MessageSquare", shortcut: "1" },
  { label: "To-Dos",       href: "/reminders",    icon: "ClipboardList", shortcut: "2" },
  { label: "Calendar",     href: "/calendar",     icon: "CalendarDays",  shortcut: "3" },
  { label: "Second Brain", href: "/second-brain", icon: "Brain",         shortcut: "4" },
  { label: "Projects",     href: "/tasks",        icon: "CheckSquare" },
  { label: "Meetings",     href: "/meetings",     icon: "Video" },
  { label: "Contacts",     href: "/contacts",     icon: "Users" },
  { label: "Feed",         href: "/feed",         icon: "Rss" },
  { label: "Agent Jobs",   href: "/agent-jobs",   icon: "Cpu" },
  { label: "Artifacts",    href: "/artifacts",    icon: "Archive" },
  { label: "Cron Manager", href: "/cron",         icon: "Clock" },
  { label: "Connectors",   href: "/connectors",   icon: "Plug" },
  { label: "Mnemon",       href: "/memory",       icon: "Database" },
  { label: "Settings",     href: "/settings",     icon: "Settings" },
] as const
